services:
  catalogue:
    build: ./catalogue
    image: rreddygang/catalogue:1.1.0
    container_name: catalogue
    depends_on:
      - mongodb

  user:
    build: ./user
    image: rreddygang/user:1.1.0
    container_name: user
    depends_on:
      - redis
      - mongodb

  cart:
    build: ./cart
    image: rreddygang/cart:1.1.0
    container_name: cart
    depends_on:
      - redis
      - catalogue

  shipping:
    build: ./shipping
    image: rreddygang/shipping:1.1.0
    container_name: shipping
    depends_on:
      - mysql
      - cart

  payment:
    build: ./payment
    image: rreddygang/payment:1.1.0
    container_name: payment
    environment:
      CART_HOST: "cart"
      CART_PORT: "8080"
      USER_HOST: "user"
      USER_PORT: "8080"
      AMQP_HOST: "rabbitmq"
      AMQP_PORT: "5672"
      AMQP_USER: "roboshop"
      AMQP_PASS: "roboshop123"
    depends_on:
      - rabbitmq
      - cart
      - user

  frontend:
    build: ./frontend
    image: rreddygang/frontend:1.1.0
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment

  mongodb:
    build: ./mongodb
    image: rreddygang/mongodb:1.1.0
    container_name: mongodb
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:7.0
    container_name: redis
    volumes:
      - redis:/data

  mysql:
    build: ./mysql
    image: rreddygang/mysql:1.1.0
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

networks:
  default:
    driver: bridge
    name: roboshop
    external: false

volumes:
  mongodb:
    driver: local
    name: mongodb
    external: false

  mysql:
    driver: local
    name: mysql
    external: false

  rabbitmq:
    driver: local
    name: rabbitmq
    external: false
    
  redis:
    driver: local
    name: redis
    external: false